### ISSUE TITLE
kedro ipython throws error while loading global commands and commands

### ISSUE THREAD

**Issue by Chouffe** [Galileo-Galilei/kedro-mlflow-tutorial#7]
When I run kedro ipython in this Kedro project, here is what I get:
```
Traceback (most recent call last):
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 683, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.1 (/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages), Requirement.parse('click==7.*'), {'uvicorn'})
Error: Loading global commands from kedro-viz = kedro_viz.launchers.cli:commands
Traceback (most recent call last):
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 683, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.1 (/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages), Requirement.parse('click<8.0'), {'kedro'})
Error: Loading global commands from kedro_mlflow = kedro_mlflow.framework.cli.cli:commands
Traceback (most recent call last):
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 683, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.1 (/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages), Requirement.parse('click<8.0'), {'kedro'})
Error: Loading project commands from kedro_mlflow = kedro_mlflow.framework.cli.cli:commands
Traceback (most recent call last):
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 683, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.1 (/home/chouffe/anaconda3/envs/kedro_mlflow_tutorial/lib/python3.7/site-packages), Requirement.parse('click==7.*'), {'uvicorn'})
Error: Loading line_magic commands from line_magic = kedro_viz.launchers.jupyter:run_viz
```

**Comment by Chouffe** [comment]
Reinstalling everything from a clean conda env worked. I am not sure how I got into that state. Closing the issue.
